version: "3.5"
name: special-agent-go
services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:15.14
    networks:
      - temporal-network
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB
      - DB_PORT
      - POSTGRES_USER
      - POSTGRES_PWD
      - POSTGRES_SEEDS
      - TEMPORAL_ADDRESS
      - TEMPORAL_CLI_ADDRESS
    env_file:
      - .env
    image: temporalio/auto-setup:1.28.0
    networks:
      - temporal-network
    ports:
      - 7233:7233

  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS
      - TEMPORAL_CLI_ADDRESS
    env_file:
      - .env
    image: temporalio/admin-tools:1.28
    networks:
      - temporal-network
    stdin_open: true
    tty: true
  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS
      - TEMPORAL_CORS_ORIGINS
      - TEMPORAL_CSRF_COOKIE_INSECURE
    env_file:
      - .env
    image: temporalio/ui:2.39.0
    networks:
      - temporal-network
    ports:
      - 8080:8080

  # temporal-worker:
  #   container_name: temporal-worker
  #   depends_on:
  #     - temporal
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile.worker
  #     target: workflow_worker
  #   environment:
  #     - TEMPORAL_ADDRESS=temporal:7233
  #     - OPENAI_API_KEY
  #     - ANTHROPIC_API_KEY
  #   env_file:
  #     - .env
  #   networks:
  #     - temporal-network
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3

  # temporal-manager-api:
  #   container_name: temporal-manager-api
  #   depends_on:
  #     - temporal
  #   build:
  #     context: ../
  #     dockerfile: docker/Dockerfile.api
  #     target: api_server
  #   environment:
  # - TEMPORAL_ADDRESS=temporal:7233
  # - OPENAI_API_KEY
  # - ANTHROPIC_API_KEY
  #   env_file:
  #     - .env
  #   networks:
  #     - temporal-network
  #   ports:
  #     - 8000:8000
  #   deploy:
  #     restart_policy:
  #       condition: on-failure
  #       delay: 5s
  #       max_attempts: 3

networks:
  temporal-network:
    driver: bridge
    name: temporal-network
